### ISSUE TITLE
Source code for new worker

### ISSUE THREAD

**Issue by martinfletcher** [Azure/azure-functions-dotnet-worker-preview#10]
@anthonychu - Apologies if I have just overlooked the repository in my searching, but is the source code for this new worker currently public?

If so, where is it located, as I would like to take a look and help out where I can.

**Comment by anthonychu** [comment]
Yes we should be able to make that public soon. @fabiocav

**Comment by ankitkumarr** [comment]
The worker is now public at -- https://github.com/Azure/azure-functions-dotnet-worker
