### ISSUE TITLE
[Question] How would I return an image via HttpResponseData (byte[] - images/jpeg)?

### ISSUE THREAD

**Issue by Zettersten** [Azure/azure-functions-dotnet-worker-preview#25]
Lets say I fetch an image using the Bing Image Search API.

It'll give me the raw stream of the image along with its content-type.

How can I turn that stream into a valid response using the HttpResponseData object?

Since "body" is the only property available and its a string, I have no idea what to do...

**Comment by Zettersten** [comment]
Problem solved.

Return a byte array and not HttpResponseData.

**Comment by hansmbakker** [comment]
How are the proper content-type headers set, then?
