### ISSUE TITLE
"No job functions found"

### ISSUE THREAD

**Issue by brminnick** [Azure/azure-functions-dotnet-worker-preview#26]
After migrating my Azure Functions to .NET 5, and running `func host start` using `Azure Functions Core Tools v3.0.3160`, it displays the following message: 

> No job functions found

## Error Message

> No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)

## Reproduction Steps

0. Install [Azure Functions Core Tools v3.0.3160](https://github.com/Azure/azure-functions-core-tools)
1. Download/clone the branch `Move-Azure-Functions-to-Net5.0` of this repo: https://github.com/brminnick/GitTrends/tree/Move-Azure-Functions-to-net5.0/
2. In Visual Studio, open **GitTrends.sln**
3. In Visual Studio, open **Backend** > **GitTrends.Functions** > **Program.cs**
4. In **Program.cs**, on line 19, replace the following line of code:

```csharp
readonly static string _token = Environment.GetEnvironmentVariable("UITestToken_brminnick") ?? string.Empty;
```

with

```csharp
readonly static string _token = "abc123";
```

> **Note**: If you prefer, you may instead enter a valid [GitHub Token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token). For this reproduction, however the `UITestToken_brminnick` just cannot be an empty string; if it is an empty string an error will be thrown at runtime.

> **Note:** If you prefer, you may instead create an Environment Variable called `UITestToken_brminnick` using a valid [GitHub Token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token).

5. Save changes to `Program.cs`
6. Open the terminal / command prompt
7. In the terminal window, navigate to the folder **GitTrends.Functions**
8. In the terminal window, enter `func host start`
9. Confirm the following message: `No job functions found`

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/13558917/104051682-5bfdb100-519d-11eb-8dbc-a889a1cae18f.png">

**Comment by fabiocav** [comment]
@brminnick can you please try this with the `preview 3` that was just released?

**Comment by brminnick** [comment]
Thanks @fabiocav!

I can confirm that I no long get the `No job functions found` error message after updating to `preview3` 👍
