### ISSUE TITLE
Do we support WEBSITE_RUN_FROM_PACKAGE with an url to the zip file

### ISSUE THREAD

**Issue by josere** [Azure/azure-functions-dotnet-worker-preview#48]
I have deployed my function using `func azure functionapp publish <APP_NAME>` and using terraform. The one with `func` works fine, but the one with terraform give me a `Azure Functions Runtime is unreachable.` error when i try to list the App files. Requesting an http trigger function fails with 502.

One mayor difference is that `func` deployed function uses WEBSITE_RUN_FROM_PACKAGE = 1, while the terraform deployed uses WEBSITE_RUN_FROM_PACKAGE = url-to-zip-file-in-storage. I was wonder if this is supported at this time.

Thanks,
Jose.

**Comment by fabiocav** [comment]
Yes, that should work. Would you mind sharing the application name so we can take a look at the logs?

**Comment by josere** [comment]
@fabiocav thanks for replying. I have deployed the same code in parallel deployments.

https://jo2-us-dbbackups-function.azurewebsites.net/api/ping works fine, and was deployed with `func azure functionapp publish jo2-us-dbbackups-function`.

https://jos-us-dbbackups-function.azurewebsites.net/api/ping fails with server error, and was deployed with terraform using WEBSITE_RUN_FROM_PACKAGE <url>. 

There might be many other differences, but is hard for me to compare them.

Regards,
Jose.

**Comment by josere** [comment]
Apparently there is no support in terraform for specifying netframeworkversion and so it defaults to v4.0.

it's in template.json
"netFrameworkVersion": "v4.0",
under properties mapping

doesn’t seem to be anything to do with either azure function 5.0 preview or azure.
