### ISSUE TITLE
Is it possible to generate several output bindings, so they can be processed independently?

### ISSUE THREAD

**Issue by josere** [Azure/azure-functions-dotnet-worker-preview#50]
`[Queue("functionstesting2", Connection = "AzureWebJobsStorage")] OutputBinding<Book> book` will let you add one book to the queue. What if I want to add many books, so they can trigger separate events, and can be processed independently?

Regards,
Jose.

**Comment by anthonychu** [comment]
You should be able to use `OutputBinding<IEnumerable<Book>>` but this is not working in preview3. Tracking this here: https://github.com/Azure/azure-functions-dotnet-worker/issues/124
